// Mocks generated by Mockito 5.0.16 from annotations
// in badger_group_up/test/integration/login/sign_in_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:badger_group_up/src/system/email_auth.dart' as _i3;
import 'package:email_auth/email_auth.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEmailAuth_0 extends _i1.Fake implements _i2.EmailAuth {}

/// A class which mocks [EmailAuthentication].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmailAuthentication extends _i1.Mock
    implements _i3.EmailAuthentication {
  MockEmailAuthentication() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.EmailAuth get emailAuthSession =>
      (super.noSuchMethod(Invocation.getter(#emailAuthSession),
          returnValue: _FakeEmailAuth_0()) as _i2.EmailAuth);
  @override
  set emailAuthSession(_i2.EmailAuth? _emailAuthSession) => super.noSuchMethod(
      Invocation.setter(#emailAuthSession, _emailAuthSession),
      returnValueForMissingStub: null);
  @override
  _i4.Future<bool> sendAuthEmail(String? email) =>
      (super.noSuchMethod(Invocation.method(#sendAuthEmail, [email]),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  bool validateOTP(String? email, String? userInput) =>
      (super.noSuchMethod(Invocation.method(#validateOTP, [email, userInput]),
          returnValue: false) as bool);
  @override
  String toString() => super.toString();
}
